/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

import org.hibernate.mapping.Value;

import co.edu.eam.ingesoft.banco.entidades.Credicart;
import co.edu.eam.ingesoft.banco.entidades.CreditcardConsume;
import co.edu.eam.ingesoft.banco.entidades.CreditcardPaymentConsume;
import co.edu.eam.ingesoft.banco.entidades.Customer;
import co.edu.eam.ingesoft.banco.entidades.Franchise;
import co.edu.eam.ingesoft.banco.entidades.Product;
import co.edu.eam.ingesoft.banco.entidades.SavingAccount;
import co.edu.eam.ingesoft.banco.entidades.Transaction;
import co.edu.eam.ingesoft.banco.entidades.enumeraciones.TipoConsumo;
import co.edu.eam.ingesoft.banco.entidades.enumeraciones.TipoTransacion;
import co.edu.eam.ingesoft.controlador.ControladorVentanaCliente;

/**
 *
 * @author CAMILO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

	private ControladorVentanaCliente controladorCliente;

	/**
	 * Creates new form VentanaPrincipal
	 */
	public VentanaPrincipal() {
		initComponents();
		this.setLocationRelativeTo(this);
		try {
			controladorCliente = new ControladorVentanaCliente();
			cargarFranquicia();
			cargarTipoTransacion();
			tipoCompra();
		} catch (NamingException e) {
			e.printStackTrace();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNumeroIdentificacion = new javax.swing.JTextField();
        jCBTipoIdentificacion = new javax.swing.JComboBox();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCBFranquicia = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCBTipoIdentificacionFranquicia = new javax.swing.JComboBox();
        jTFNumeroIdentificacionFranquicia = new javax.swing.JTextField();
        jBAsignarTarjeta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTFMonto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTFNumeroIdentificacionCuenta = new javax.swing.JTextField();
        jCBTipoIdentificacionCuenta = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JTFMontoCuenta = new javax.swing.JTextField();
        jBAsignarCuenta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTFMontoTransaccion = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jBGuardarTransaccion = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jCBTipoTrans = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTFNumCuenta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFFuenteTransaccion = new javax.swing.JTextField();
        jTFCuentaTransferrir = new javax.swing.JTextField();
        jLcuentaT = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTFNumTarjetaCredito = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTFValorCuenta = new javax.swing.JTextField();
        jTFRegistrarCompra = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTFNumCuotas = new javax.swing.JTextField();
        jCBTipoCompra = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTFnumTarjetaPago = new javax.swing.JTextField();
        jTFValorPago = new javax.swing.JTextField();
        jCBRegistrarPago = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jTabbedPane1.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel2.setText("Numero de identificación");

        jLabel3.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel3.setText("Tipo identificaicon");

        jLabel4.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel4.setText("Nombre ");

        jLabel5.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel5.setText("Apellido");

        jTFNumeroIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jCBTipoIdentificacion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCBTipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Cedula", "Pasaporte", "Tarjeta Identidad" }));

        jTFNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTFApellido.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jBGuardar.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNumeroIdentificacion)
                            .addComponent(jCBTipoIdentificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFApellido)
                            .addComponent(jTFNombre))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBTipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Cliente", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel6.setText("Franquicia");

        jCBFranquicia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel7.setText("Numero de identificación");

        jLabel8.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel8.setText("Tipo de identificación");

        jCBTipoIdentificacionFranquicia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCBTipoIdentificacionFranquicia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Cedula", "Pasaporte", "Tarjeta Identidad" }));

        jTFNumeroIdentificacionFranquicia.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jBAsignarTarjeta.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jBAsignarTarjeta.setText("Asignar tarjeta");
        jBAsignarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarTarjetaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel9.setText("Monto");

        jTFMonto.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 19)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAsignarTarjeta)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFNumeroIdentificacionFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(67, 67, 67)
                            .addComponent(jCBTipoIdentificacionFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNumeroIdentificacionFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jCBTipoIdentificacionFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jTFMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(29, 29, 29)
                .addComponent(jBAsignarTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Targeta de credito", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTFNumeroIdentificacionCuenta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jCBTipoIdentificacionCuenta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCBTipoIdentificacionCuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Cedula", "Pasaporte", "Tarjeta Identidad" }));

        jLabel10.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel10.setText("Tipo de identificación");

        jLabel11.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel11.setText("Numero de identificación");

        jLabel12.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel12.setText("Monto");

        JTFMontoCuenta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jBAsignarCuenta.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jBAsignarCuenta.setText("AsignarCuenta");
        jBAsignarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAsignarCuenta)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNumeroIdentificacionCuenta)
                            .addComponent(jCBTipoIdentificacionCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTFMontoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTFNumeroIdentificacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCBTipoIdentificacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTFMontoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(49, 49, 49)
                .addComponent(jBAsignarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuenta de Ahorro", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTFMontoTransaccion.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel15.setText("Monto");

        jBGuardarTransaccion.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jBGuardarTransaccion.setText("Guardar");
        jBGuardarTransaccion.setPreferredSize(new java.awt.Dimension(109, 34));
        jBGuardarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarTransaccionActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel16.setText("Tipo transaccion");

        jCBTipoTrans.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jCBTipoTrans.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoTransItemStateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel17.setText("Numero de cuenta  origen");

        jTFNumCuenta.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel13.setText("Fuente de transaccion");

        jTFFuenteTransaccion.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N

        jLcuentaT.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLcuentaT.setText("Cuenta ha transferir saldo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGuardarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLcuentaT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFMontoTransaccion)
                            .addComponent(jCBTipoTrans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFNumCuenta)
                            .addComponent(jTFFuenteTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jTFCuentaTransferrir))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBTipoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFMontoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFuenteTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCuentaTransferrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcuentaT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jBGuardarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transacciones", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel18.setText("Numero de la tarjeta de credito");

        jTFNumTarjetaCredito.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel19.setText("Valor");

        jTFValorCuenta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTFRegistrarCompra.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jTFRegistrarCompra.setText("Registrar Consumo");
        jTFRegistrarCompra.setPreferredSize(new java.awt.Dimension(157, 41));
        jTFRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFRegistrarCompraActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel20.setText("Numero de cuotas");

        jTFNumCuotas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jCBTipoCompra.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCBTipoCompra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoCompraItemStateChanged(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 20)); // NOI18N
        jLabel21.setText("Tipo de consumo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNumTarjetaCredito)
                            .addComponent(jTFValorCuenta)
                            .addComponent(jTFNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNumTarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFValorCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTFNumCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jTFRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consumo tarjeta credito", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Numero tarjeta de credito");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel23.setText("Valor a pagar");

        jTFnumTarjetaPago.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTFValorPago.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jCBRegistrarPago.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCBRegistrarPago.setText("Registrar");
        jCBRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRegistrarPagoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Consultar Cuota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCBRegistrarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFnumTarjetaPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFValorPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTFnumTarjetaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTFValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jCBRegistrarPago)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pagos Tarjeta Credito", jPanel7);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Dancing in the Moonlight", 1, 120)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Banco Armenia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTipoTransItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoTransItemStateChanged
        if(jCBTipoTrans.getSelectedIndex()==0){
        	jLcuentaT.setVisible(true);
        	jTFCuentaTransferrir.setVisible(true);
        }else{
        	jLcuentaT.setVisible(false);
        	jTFCuentaTransferrir.setVisible(false);
        }
    }//GEN-LAST:event_jCBTipoTransItemStateChanged

    private void jTFRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFRegistrarCompraActionPerformed
        
    	try{
    		CreditcardConsume consumotarjeta = new CreditcardConsume();
    		
    		consumotarjeta.setAmmount(Double.parseDouble(jTFValorCuenta.getText()));
    		consumotarjeta.setNumber_shares(Integer.parseInt(jTFNumCuotas.getText()));
    		
    		TipoConsumo tipoCon = (TipoConsumo) jCBTipoCompra.getSelectedItem();
    		
    		controladorCliente.registrarConsumo(consumotarjeta,jTFNumTarjetaCredito.getText(),tipoCon);
    		JOptionPane.showMessageDialog(null, "Registro de compra con éxito");
    		
    	}catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
    	
    	
    	
    }//GEN-LAST:event_jTFRegistrarCompraActionPerformed

    private void jCBTipoCompraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBTipoCompraItemStateChanged
        if(jCBTipoCompra.getSelectedIndex()== 0){
            jTFNumCuotas.setVisible(false);
            jTFNumCuotas.setText("0");
            jLabel20.setVisible(false);
            
        }else{
            jTFNumCuotas.setVisible(true);
            jLabel20.setVisible(true);
            jTFNumCuotas.setText("");


        }
    }//GEN-LAST:event_jCBTipoCompraItemStateChanged

    private void jCBRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRegistrarPagoActionPerformed

    	try{
    		    		
    		controladorCliente.pagoTarjeta(Double.parseDouble(jTFValorPago.getText()),jTFnumTarjetaPago.getText());
    		
    		JOptionPane.showMessageDialog(null, "Pago registrado");
    		
    	}catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
    
    }//GEN-LAST:event_jCBRegistrarPagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    	try{
    		double total = controladorCliente.consultarCuota(jTFnumTarjetaPago.getText());
    		JOptionPane.showMessageDialog(null, "El saldo de la cuota es de: "+total);
    	}catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
    	
    }//GEN-LAST:event_jButton1ActionPerformed

	private void jBAsignarCuentaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAsignarCuentaActionPerformed
		try {

			SavingAccount cuenta = new SavingAccount();

			cuenta.setAmmount(Double.parseDouble(JTFMontoCuenta.getText()));

			controladorCliente.crearCuentaAhorro(cuenta, jTFNumeroIdentificacionCuenta.getText(),
					(String) jCBTipoIdentificacionCuenta.getSelectedItem());

			JOptionPane.showMessageDialog(null, "Cuenta creada con exito");

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
	}// GEN-LAST:event_jBAsignarCuentaActionPerformed

	private void jBGuardarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGuardarTransaccionActionPerformed
		try {

			Transaction trans = new Transaction();
			trans.setTipoTransaccion((TipoTransacion) jCBTipoTrans.getSelectedItem());
			trans.setAmmount(Double.parseDouble(jTFMontoTransaccion.getText()));
			trans.setSourceTransaction(jTFFuenteTransaccion.getText());

			controladorCliente.crearTransaccion(trans, jTFNumCuenta.getText(),jTFCuentaTransferrir.getText());
			JOptionPane.showMessageDialog(null, "Transaccion registrada con exito");

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage());
		}
	}// GEN-LAST:event_jBGuardarTransaccionActionPerformed

	private void jBAsignarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAsignarTarjetaActionPerformed

		try {

			Credicart tarjeta = new Credicart();

			tarjeta.setFranchise((Franchise) jCBFranquicia.getSelectedItem());
			tarjeta.setMonto(Double.parseDouble(jTFMonto.getText()));

			controladorCliente.crearTarjetaCredito(tarjeta, jTFNumeroIdentificacionFranquicia.getText(),
					(String) jCBTipoIdentificacionFranquicia.getSelectedItem());

			JOptionPane.showMessageDialog(null, "Tarjeta creada con exito");

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
		}

	}// GEN-LAST:event_jBAsignarTarjetaActionPerformed

	private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGuardarActionPerformed

		try {
			Customer cliente = new Customer();
			cliente.setName(jTFNombre.getText());
			cliente.setLastName(jTFApellido.getText());
			cliente.setTipoIdentificacion((String) jCBTipoIdentificacion.getSelectedItem());
			cliente.setNumeroIndentificacion(jTFNumeroIdentificacion.getText());

			controladorCliente.crearCliente(cliente);
			JOptionPane.showMessageDialog(null, "Cliente creado");

		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_jBGuardarActionPerformed

	private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBuscarActionPerformed

		try {

			String num = jTFNumeroIdentificacion.getText();
			String tipo = (String) jCBTipoIdentificacion.getSelectedItem();

			Customer cliente = controladorCliente.buscarCliente(num, tipo);
			if (cliente != null) {
				jTFNombre.setText(cliente.getName());
				jTFApellido.setText(cliente.getLastName());
			} else {
				JOptionPane.showMessageDialog(null, "Cliente no registrado");
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_jBBuscarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaPrincipal().setVisible(true);
			}
		});
	}

	public void cargarFranquicia() {
		try {
			List<Franchise> listaFran = controladorCliente.listaFranquicia();

			for (Franchise franquicia : listaFran) {
				jCBFranquicia.addItem(franquicia);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void cargarTipoTransacion() {

		TipoTransacion[] listTipoT = TipoTransacion.values();
		for (int i=0;i<3;i++) {
			jCBTipoTrans.addItem(listTipoT[i]);
		}

	}
	
	
	public void tipoCompra(){
		TipoConsumo [] listTopoC = TipoConsumo.values();
		for(TipoConsumo consumo: listTopoC){
			jCBTipoCompra.addItem(consumo);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFMontoCuenta;
    private javax.swing.JButton jBAsignarCuenta;
    private javax.swing.JButton jBAsignarTarjeta;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBGuardarTransaccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBFranquicia;
    private javax.swing.JButton jCBRegistrarPago;
    private javax.swing.JComboBox jCBTipoCompra;
    private javax.swing.JComboBox jCBTipoIdentificacion;
    private javax.swing.JComboBox jCBTipoIdentificacionCuenta;
    private javax.swing.JComboBox jCBTipoIdentificacionFranquicia;
    private javax.swing.JComboBox jCBTipoTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLcuentaT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFCuentaTransferrir;
    private javax.swing.JTextField jTFFuenteTransaccion;
    private javax.swing.JTextField jTFMonto;
    private javax.swing.JTextField jTFMontoTransaccion;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNumCuenta;
    private javax.swing.JTextField jTFNumCuotas;
    private javax.swing.JTextField jTFNumTarjetaCredito;
    private javax.swing.JTextField jTFNumeroIdentificacion;
    private javax.swing.JTextField jTFNumeroIdentificacionCuenta;
    private javax.swing.JTextField jTFNumeroIdentificacionFranquicia;
    private javax.swing.JButton jTFRegistrarCompra;
    private javax.swing.JTextField jTFValorCuenta;
    private javax.swing.JTextField jTFValorPago;
    private javax.swing.JTextField jTFnumTarjetaPago;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
